openapi: 3.0.1
info:
  title: CalendarApp API
  version: v1
  description: API for managing calendar appointments
servers:
  - url: http://localhost:5000/api
paths:
  /appointments:
    get:
      summary: Get all appointments
      tags:
        - Appointments
      responses:
        "200":
          description: List of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Appointment"
    post:
      summary: Create a new appointment
      tags:
        - Appointments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Appointment"
      responses:
        "201":
          description: Appointment created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        "409":
          description: Conflict (overlapping appointment)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /appointments/{id}:
    put:
      summary: Update an appointment
      tags:
        - Appointments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Appointment"
      responses:
        "200":
          description: Updated appointment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appointment"
        "404":
          description: Appointment not found
        "409":
          description: Conflict (overlapping appointment)
    delete:
      summary: Delete an appointment
      tags:
        - Appointments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Appointment deleted successfully
        "404":
          description: Appointment not found
components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        isAllDay:
          type: boolean
        location:
          type: string
        attendees:
          type: string
