openapi: 3.0.1
info:
  title: Backend
  version: '1.0'
paths:
  /api/Appointments:
    get:
      tags:
        - Appointments
      responses:
        '200':
          description: Success
    post:
      tags:
        - Appointments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          text/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Success
  '/api/Appointments/{id}':
    put:
      tags:
        - Appointments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          text/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Appointments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        isAllDay:
          type: boolean
        location:
          type: string
          nullable: true
        attendees:
          type: string
          nullable: true
      additionalProperties: false